tnc-openstack add subcommand 'registry'

diff --git a/kollatest b/kollatest
--- a/kollatest
+++ b/kollatest
@@ -1,17 +1,49 @@
 #!/bin/bash
 
+# default
+USERN="username"
+PASSW="password"
+HOST1="1.2.3.4"
+PORT1="5000"
+REGISTRY_DIR="/home/kolla-registry"
+myname=$0
+
+# override above settings
+[ -f  ~/.kollatest_rc ] && { . ~/.kollatest_rc ; true; } || { echo "RC file ~/.kollatest_rc not found."; }
+
+# options have highest priority
+while getopts ":u:p:h:P:d:t:" opt; do
+   case $opt in
+        u ) USERN=$OPTARG
+            ;;
+        p ) PASSW=$OPTARG
+            ;;
+        h ) HOST1=$OPTARG
+            ;;
+        P ) PORT1=$OPTARG
+            ;;
+        d ) REGISTRY_DIR=$OPTARG
+            ;;
+        t ) myname=$OPTARG
+            ;;
+        ? ) echo "error input"
+            exit 1;;
+   esac
+done
+shift $(($OPTIND - 1))
+
 if [ $# -eq 0 ];then
   echo -e "create/push/print docker registry."
-  echo -e "Usage:\n\t$0 [options...] create|push|print|cp-cert [PARAMETERS...]"
+  echo -e "Usage:\n\t$myname [options...] create|push|print|cp-cert [PARAMETERS...]"
   echo -e "\nExamples:"
   echo -e "    create docker registry (must be run on the registry host)"
-  echo -e "        # $0 [-u username] [-p password] [-h host] [-P port] [-d registry_directory] create\n"
+  echo -e "        # $myname [-u username] [-p password] [-h host] [-P port] [-d registry_directory] create\n"
   echo -e "    push local docker imges to registry host"
-  echo -e "        # $0 [-u username] [-p password] [-h host] [-P port] push [[REPOSITORY[:TAG]]]\n"
+  echo -e "        # $myname [-u username] [-p password] [-h host] [-P port] push [[REPOSITORY[:TAG]]]\n"
   echo -e "    print repositories w/ tags in docker registry"
-  echo -e "        # $0 [-u username] [-p password] [-h host] [-P port] print\n"
+  echo -e "        # $myname [-u username] [-p password] [-h host] [-P port] print\n"
   echo -e "    copy certificate to remote host (must be run on the registry host after 'create')"
-  echo -e "        # $0 [-d registry_directory] cp-cert <remote>"
+  echo -e "        # $myname [-d registry_directory] cp-cert <remote>"
   echo -e "\nOptions:"
   echo -e "    -h host                  docker registry hostname or ip address"
   echo -e "    -P port                  docker registry service listen port"
@@ -28,35 +60,6 @@ if [ $# -eq 0 ];then
   echo -e "        REGISTRY_DIR=\"/home/kolla-registry\""
   exit 0
 fi
-
-# default
-USERN="username"
-PASSW="password"
-HOST1="1.2.3.4"
-PORT1="5000"
-REGISTRY_DIR="/home/kolla-registry"
-
-# override above settings
-[ -f  ~/.kollatest_rc ] && { . ~/.kollatest_rc ; true; } || { echo "RC file ~/.kollatest_rc not found."; }
-
-# options have highest priority
-while getopts ":u:p:h:P:d:" opt; do
-   case $opt in
-        u ) USERN=$OPTARG
-            ;;
-        p ) PASSW=$OPTARG
-            ;;
-        h ) HOST1=$OPTARG
-            ;;
-        P ) PORT1=$OPTARG
-            ;;
-        d ) REGISTRY_DIR=$OPTARG
-            ;;
-        ? ) echo "error input"
-            exit 1;;
-   esac
-done
-shift $(($OPTIND - 1))
 
 while [ -z "$USERN" ]; do
     read -p "Input username: " USERN
